CREATE SEQUENCE SEQ_MEMBER;


CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER DEFAULT 0,
	MEMBER_GENDER NUMBER DEFAULT 3,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'SANGHUN@NAVER.COM', '1234', 'SANGHUN', 20, 1, SYSDATE, SYSDATE
);

SELECT * FROM TBL_MEMBER;