CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255) NOT NULL,
	POST_ID NUMBER,
	MEMBER_ID NUMBER,
	CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REPLY_POST_ID FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID),
    CONSTRAINT FK_REPLY_MEMBER_ID FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID)    
);
SELECT * FROM TBL_REPLY;