CREATE TABLE TBL_STUDENT(
	ID NUMBER CONSTRAINT PK_SUTDENT PRIMARY KEY,
	STUDENT_NAME VARCHAR2(255) NOT NULL
);

/*TBL_STUDENT 테이블에서 ID와 STUDENT_NAME 전체 조회*/
SELECT ID, STUDENT_NAME FROM TBL_STUDENT;

/*ID는 1, NAME은 한동석 값 삽입*/
INSERT INTO TBL_STUDENT (ID, STUDENT_NAME)
VALUES(1, '한동석');

/*ID가 1인 NAME을 홍길동으로 변경*/
UPDATE TBL_STUDENT
SET STUDENT_NAME ='홍길동'
WHERE ID = 1;

/*TBL_SUTUDET에서 ID가 1인 데이터 삭제*/
DELETE FROM TBL_STUDENT
WHERE ID = 1;

/*동물원*/
CREATE TABLE TBL_ZOO(
   ID NUMBER CONSTRAINT PK_ZOO PRIMARY KEY,
   ZOO_NAME VARCHAR2(255),
   ZOO_ADDRESS VARCHAR2(255),
   ZOO_ADDRESS_DETAIL VARCHAR2(255),
   ZOO_MAX_ANIMAL NUMBER DEFAULT 0
);

/*동물*/
CREATE TABLE TBL_ANIMAL(
   ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
   ANIMAL_NAME VARCHAR2(255),
   ANIMAL_TYPE VARCHAR2(255),
   ANIMAL_AGE NUMBER DEFAULT 0,
   ANIMAL_HEIGHT NUMBER(16, 5),
   ANIMAL_WEIGHT NUMBER(16, 5),
   ZOO_ID NUMBER,
   CONSTRAINT FK_ANIMAL_ZOO FOREIGN KEY(ZOO_ID)
   REFERENCES TBL_ZOO(ID)
);
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_HEIGHT NUMBER(16,5));
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_WEIGHT NUMBER(16,5));

/*알아서 매번 다음 SEQUENCE를 가져와준다. */
/*시퀀스를 직접 만들어서 사용해야 한다.*/
CREATE SEQUENCE SEQ_ZOO;


SELECT * FROM TBL_ZOO;
INSERT INTO TBL_ZOO
VALUES(SEQ_ZOO.NEXTVAL, '서울랜드', '서울', '랜드', 100);

INSERT INTO TBL_ZOO
VALUES(SEQ_ZOO.NEXTVAL, '에버랜드', '경기', '용인', 500);

UPDATE TBL_ZOO 
SET ZOO_MAX_ANIMAL  = 5000
WHERE ZOO_NAME = '에버랜드';

DELETE FROM TBL_ZOO
WHERE ID = 1;

CREATE SEQUENCE SEQ_ANIMAL;
SELECT * FROM TBL_ANIMAL;
INSERT INTO TBL_ANIMAL 
VALUES(SEQ_ANIMAL.NEXTVAL, '사자', '맹수',3,87.5,120.242,2);

INSERT INTO TBL_ANIMAL 
VALUES(SEQ_ANIMAL.NEXTVAL, '악어', '도마뱀',12,300.5,180.242,2);

/*에버랜드(2) 동물원의 동물만 조회*/
SELECT ID ,ANIMAL_NAME ,ANIMAL_TYPE ,ANIMAL_AGE ,ANIMAL_HEIGHT ,ANIMAL_WEIGHT ,ZOO_ID 
FROM TBL_ANIMAL
WHERE ZOO_ID =2;

/****************************************************************************************************************************/
/****************************************************************************************************************************/
/****************************************************************************************************************************/
/*<구현>*/
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_ID VARCHAR2(1000) CONSTRAINT UK_USER UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(1000) NOT NULL,
	USER_NAME VARCHAR2(1000) NOT NULL,
	USER_ADDRESS VARCHAR2(1000) NOT NULL,
	USER_EMAIL VARCHAR2(1000) NOT NULL,
	USER_BIRTHDAY DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_DATE DATE DEFAULT CURRENT_TIMESTAMP,
	USER_ID NUMBER,
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
    REFERENCES TBL_USER(ID),
    PRODUCT_ID NUMBER,
    CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
    REFERENCES TBL_PRODUCT(ID)
);

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(2000) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_INVENTORY NUMBER DEFAULT 0
);


/*각 테이블에 3개 이상씩 정보를 추가하고, 조회한다*/
/*수정 2회*/
/*삭제 2회*/
CREATE SEQUENCE SEQ_USER;
SELECT * FROM TBL_USER;
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'DDDDD', '1111', '상훈', '서울 강남', 'SEKKF@GMAIL.COM', '2001-11-11');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'AEFEF', '2222', '길동', '강원도', 'QGEQRF@GMAIL.COM', '2010-01-03');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'ADFASDF', '3333', '야호', '충청북도', 'CNDQNR@GMAIL.COM', '3000-11-23');

UPDATE TBL_USER 
SET USER_ID ='AAAAA'
WHERE ID = 1;
UPDATE TBL_USER 
SET USER_ADDRESS ='하와이'
WHERE ID = 2;

DELETE FROM TBL_USER
WHERE ID = 3;

/*사용하고 있는 PRODUCT가 있어서 삭제 불가*/
DELETE FROM TBL_USER
WHERE ID = 1;


CREATE SEQUENCE SEQ_PRODUCT;
SELECT * FROM TBL_PRODUCT;
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL,'상품1', 20000, 300);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL,'상품2', 50500, 100);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL,'상품3', 13100, 200);


CREATE SEQUENCE SEQ_ORDER;
SELECT * FROM TBL_ORDER;
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, '2000-10-16', '1','2');
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, '2000-10-18', '1','3');
INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, '2000-11-18', '2','2');

















